quest_create_mis goal_state_0, 0
quest_create_mis goal_visible_0, 1
quest_create_mis goal_type_0, 1
quest_create_mis goal_target_0, 148
quest_create_mis goal_state_1, 0
quest_create_mis goal_visible_1, 1
quest_create_mis goal_type_1, 3
quest_create_mis goal_loot_1, 1000
quest_create_mis goal_max_diff_1, 0
quest_create_mis goal_state_2, 0
quest_create_mis goal_visible_2, 1
quest_create_mis goal_type_2, 3
quest_create_mis goal_loot_2, 1500
quest_create_mis goal_min_diff_2, 1
quest_create_mis goal_max_diff_2, 1
quest_create_mis goal_state_3, 0
quest_create_mis goal_visible_3, 1
quest_create_mis goal_type_3, 3
quest_create_mis goal_loot_3, 2000
quest_create_mis goal_min_diff_3, 2
quest_create_mis goal_state_4, 0
quest_create_mis goal_visible_4, 1
quest_create_mis goal_type_4, 2
quest_create_mis goal_target_4, -14
quest_create_mis goal_reverse_4, 1
quest_create_mis goal_min_diff_4, 2
quest_create_mis goal_state_5, 0
quest_create_mis goal_visible_5, 1
quest_create_mis goal_type_5, 4
quest_create_mis goal_target_5, 454
quest_create_mis goal_final_5, 1
quest_create_mis goal_min_diff_5, 1
